// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: assets/transactions/renumerate/service.proto

package com.assetmantle.modules.assets.transactions.renumerate;

public final class ServiceProto {
  private ServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,assets/transactions/renumerate/service" +
      ".proto\0222assetmantle.modules.assets.trans" +
      "actions.renumerate\032\034google/api/annotatio" +
      "ns.proto\032,assets/transactions/renumerate" +
      "/message.proto\0329assets/transactions/renu" +
      "merate/transaction_response.proto2\275\001\n\007Se" +
      "rvice\022\261\001\n\006Handle\022;.assetmantle.modules.a" +
      "ssets.transactions.renumerate.Message\032G." +
      "assetmantle.modules.assets.transactions." +
      "renumerate.TransactionResponse\"!\202\323\344\223\002\033\"\031" +
      "/mantle/assets/renumerateB\365\002\n6com.assetm" +
      "antle.modules.assets.transactions.renume" +
      "rateB\014ServiceProtoP\001Z?github.com/AssetMa" +
      "ntle/modules/x/assets/transactions/renum" +
      "erate\242\002\005AMATR\252\0022Assetmantle.Modules.Asse" +
      "ts.Transactions.Renumerate\312\0022Assetmantle" +
      "\\Modules\\Assets\\Transactions\\Renumerate\342" +
      "\002>Assetmantle\\Modules\\Assets\\Transaction" +
      "s\\Renumerate\\GPBMetadata\352\0026Assetmantle::" +
      "Modules::Assets::Transactions::Renumerat" +
      "eb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.assetmantle.modules.assets.transactions.renumerate.MessageProto.getDescriptor(),
          com.assetmantle.modules.assets.transactions.renumerate.TransactionResponseProto.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.assetmantle.modules.assets.transactions.renumerate.MessageProto.getDescriptor();
    com.assetmantle.modules.assets.transactions.renumerate.TransactionResponseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
