# --- !Ups

ALTER TABLE BLOCKCHAIN_TRANSACTION."NFTPublicListing"
    DROP COLUMN IF EXISTS "broadcasted";
ALTER TABLE BLOCKCHAIN_TRANSACTION."NFTSale"
    DROP COLUMN IF EXISTS "broadcasted";
ALTER TABLE BLOCKCHAIN_TRANSACTION."SendCoin"
    DROP COLUMN IF EXISTS "broadcasted";


# --- !Downs
