// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/orders/internal/genesis/genesisState.v1.proto

package com.orders;

public interface GenesisStateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:orders.GenesisState)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .orders.Mappable mappables = 1 [json_name = "mappables"];</code>
   */
  java.util.List<com.orders.Mappable> 
      getMappablesList();
  /**
   * <code>repeated .orders.Mappable mappables = 1 [json_name = "mappables"];</code>
   */
  com.orders.Mappable getMappables(int index);
  /**
   * <code>repeated .orders.Mappable mappables = 1 [json_name = "mappables"];</code>
   */
  int getMappablesCount();
  /**
   * <code>repeated .orders.Mappable mappables = 1 [json_name = "mappables"];</code>
   */
  java.util.List<? extends com.orders.MappableOrBuilder> 
      getMappablesOrBuilderList();
  /**
   * <code>repeated .orders.Mappable mappables = 1 [json_name = "mappables"];</code>
   */
  com.orders.MappableOrBuilder getMappablesOrBuilder(
      int index);

  /**
   * <code>repeated .parameters.Parameter parameters = 2 [json_name = "parameters"];</code>
   */
  java.util.List<com.parameters.Parameter> 
      getParametersList();
  /**
   * <code>repeated .parameters.Parameter parameters = 2 [json_name = "parameters"];</code>
   */
  com.parameters.Parameter getParameters(int index);
  /**
   * <code>repeated .parameters.Parameter parameters = 2 [json_name = "parameters"];</code>
   */
  int getParametersCount();
  /**
   * <code>repeated .parameters.Parameter parameters = 2 [json_name = "parameters"];</code>
   */
  java.util.List<? extends com.parameters.ParameterOrBuilder> 
      getParametersOrBuilderList();
  /**
   * <code>repeated .parameters.Parameter parameters = 2 [json_name = "parameters"];</code>
   */
  com.parameters.ParameterOrBuilder getParametersOrBuilder(
      int index);
}
