// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/orders/internal/genesis/genesis.v1.proto

package com.orders;

public final class GenesisV1Proto {
  private GenesisV1Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orders_Genesis_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orders_Genesis_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n0modules/orders/internal/genesis/genesi" +
      "s.v1.proto\022\006orders\032\024gogoproto/gogo.proto" +
      "\0322modules/orders/internal/mappable/mappa" +
      "ble.v1.proto\032)schema/parameters/base/par" +
      "ameter.v1.proto\"v\n\007Genesis\022.\n\tmappables\030" +
      "\001 \003(\0132\020.orders.MappableR\tmappables\0225\n\npa" +
      "rameters\030\002 \003(\0132\025.parameters.ParameterR\np" +
      "arameters:\004\210\240\037\000B\224\001\n\ncom.ordersB\016GenesisV" +
      "1ProtoP\001Z>github.com/AssetMantle/modules" +
      "/modules/orders/internal/genesis\242\002\003OXX\252\002" +
      "\006Orders\312\002\006Orders\342\002\022Orders\\GPBMetadata\352\002\006" +
      "Ordersb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gogoproto.GogoProto.getDescriptor(),
          com.orders.MappableV1Proto.getDescriptor(),
          com.parameters.ParameterV1Proto.getDescriptor(),
        });
    internal_static_orders_Genesis_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_orders_Genesis_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orders_Genesis_descriptor,
        new java.lang.String[] { "Mappables", "Parameters", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.goprotoGetters);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.gogoproto.GogoProto.getDescriptor();
    com.orders.MappableV1Proto.getDescriptor();
    com.parameters.ParameterV1Proto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
