// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/orders/internal/mappable/mappable.v1.proto

package com.orders;

public interface MappableOrBuilder extends
    // @@protoc_insertion_point(interface_extends:orders.Mappable)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.documents.Document order = 1 [json_name = "order"];</code>
   * @return Whether the order field is set.
   */
  boolean hasOrder();
  /**
   * <code>.documents.Document order = 1 [json_name = "order"];</code>
   * @return The order.
   */
  com.documents.Document getOrder();
  /**
   * <code>.documents.Document order = 1 [json_name = "order"];</code>
   */
  com.documents.DocumentOrBuilder getOrderOrBuilder();
}
