// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: orders/transactions/modify/message.proto

package com.assetmantle.modules.orders.transactions.modify;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_assetmantle_modules_orders_transactions_modify_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_assetmantle_modules_orders_transactions_modify_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(orders/transactions/modify/message.pro" +
      "to\022.assetmantle.modules.orders.transacti" +
      "ons.modify\032\032ids/base/identity_id.proto\032\027" +
      "ids/base/order_id.proto\032\036lists/base/prop" +
      "erty_list.proto\032\027types/base/height.proto" +
      "\"\211\004\n\007Message\022\022\n\004from\030\001 \001(\tR\004from\022A\n\010from" +
      "_i_d\030\002 \001(\0132\'.assetmantle.schema.ids.base" +
      ".IdentityIDR\006fromID\022@\n\torder_i_d\030\003 \001(\0132$" +
      ".assetmantle.schema.ids.base.OrderIDR\007or" +
      "derID\022.\n\023maker_ownable_split\030\004 \001(\tR\021make" +
      "rOwnableSplit\022.\n\023taker_ownable_split\030\005 \001" +
      "(\tR\021takerOwnableSplit\022D\n\nexpires_in\030\006 \001(" +
      "\0132%.assetmantle.schema.types.base.Height" +
      "R\texpiresIn\022c\n\027mutable_meta_properties\030\007" +
      " \001(\0132+.assetmantle.schema.lists.base.Pro" +
      "pertyListR\025mutableMetaProperties\022Z\n\022muta" +
      "ble_properties\030\010 \001(\0132+.assetmantle.schem" +
      "a.lists.base.PropertyListR\021mutableProper" +
      "tiesB\335\002\n2com.assetmantle.modules.orders." +
      "transactions.modifyB\014MessageProtoP\001Z;git" +
      "hub.com/AssetMantle/modules/x/orders/tra" +
      "nsactions/modify\242\002\005AMOTM\252\002.Assetmantle.M" +
      "odules.Orders.Transactions.Modify\312\002.Asse" +
      "tmantle\\Modules\\Orders\\Transactions\\Modi" +
      "fy\342\002:Assetmantle\\Modules\\Orders\\Transact" +
      "ions\\Modify\\GPBMetadata\352\0022Assetmantle::M" +
      "odules::Orders::Transactions::Modifyb\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.assetmantle.schema.ids.base.IdentityIdProto.getDescriptor(),
          com.assetmantle.schema.ids.base.OrderIdProto.getDescriptor(),
          com.assetmantle.schema.lists.base.PropertyListProto.getDescriptor(),
          com.assetmantle.schema.types.base.HeightProto.getDescriptor(),
        });
    internal_static_assetmantle_modules_orders_transactions_modify_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_assetmantle_modules_orders_transactions_modify_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_assetmantle_modules_orders_transactions_modify_Message_descriptor,
        new java.lang.String[] { "From", "FromID", "OrderID", "MakerOwnableSplit", "TakerOwnableSplit", "ExpiresIn", "MutableMetaProperties", "MutableProperties", });
    com.assetmantle.schema.ids.base.IdentityIdProto.getDescriptor();
    com.assetmantle.schema.ids.base.OrderIdProto.getDescriptor();
    com.assetmantle.schema.lists.base.PropertyListProto.getDescriptor();
    com.assetmantle.schema.types.base.HeightProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
