// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/metas/internal/transactions/reveal/message.v1.proto

package com.metas.transactions.reveal;

public final class MessageV1Proto {
  private MessageV1Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metas_transactions_reveal_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_metas_transactions_reveal_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n;modules/metas/internal/transactions/re" +
      "veal/message.v1.proto\022\031metas.transaction" +
      "s.reveal\032!schema/data/base/anyData.v1.pr" +
      "oto\032#schema/ids/base/identityID.v1.proto" +
      "\"@\n\007Message\022\022\n\004from\030\001 \001(\tR\004from\022!\n\004data\030" +
      "\002 \001(\0132\r.data.AnyDataR\004dataB\200\002\n\035com.metas" +
      ".transactions.revealB\016MessageV1ProtoP\001ZI" +
      "github.com/AssetMantle/modules/modules/m" +
      "etas/internal/transactions/reveal\242\002\003MTR\252" +
      "\002\031Metas.Transactions.Reveal\312\002\031Metas\\Tran" +
      "sactions\\Reveal\342\002%Metas\\Transactions\\Rev" +
      "eal\\GPBMetadata\352\002\033Metas::Transactions::R" +
      "evealb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.data.AnyDataV1Proto.getDescriptor(),
          com.ids.IdentityIDV1Proto.getDescriptor(),
        });
    internal_static_metas_transactions_reveal_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_metas_transactions_reveal_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_metas_transactions_reveal_Message_descriptor,
        new java.lang.String[] { "From", "Data", });
    com.data.AnyDataV1Proto.getDescriptor();
    com.ids.IdentityIDV1Proto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
