// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/transactions/unprovision/transactionResponse.v1.proto

package com.identities.transactions.unprovision;

public final class TransactionResponseV1Proto {
  private TransactionResponseV1Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_identities_transactions_unprovision_TransactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_identities_transactions_unprovision_TransactionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nQmodules/identities/internal/transactio" +
      "ns/unprovision/transactionResponse.v1.pr" +
      "oto\022#identities.transactions.unprovision" +
      "\"\025\n\023TransactionResponseB\310\002\n\'com.identiti" +
      "es.transactions.unprovisionB\032Transaction" +
      "ResponseV1ProtoP\001ZSgithub.com/AssetMantl" +
      "e/modules/modules/identities/internal/tr" +
      "ansactions/unprovision\242\002\003ITU\252\002#Identitie" +
      "s.Transactions.Unprovision\312\002#Identities\\" +
      "Transactions\\Unprovision\342\002/Identities\\Tr" +
      "ansactions\\Unprovision\\GPBMetadata\352\002%Ide" +
      "ntities::Transactions::Unprovisionb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_identities_transactions_unprovision_TransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_identities_transactions_unprovision_TransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_identities_transactions_unprovision_TransactionResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
