// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/lists/base/idList.v1.proto

package com.lists;

/**
 * Protobuf type {@code lists.IDList}
 */
public final class IDList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:lists.IDList)
    IDListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use IDList.newBuilder() to construct.
  private IDList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private IDList() {
    iDList_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new IDList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.lists.IdListV1Proto.internal_static_lists_IDList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.lists.IdListV1Proto.internal_static_lists_IDList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.lists.IDList.class, com.lists.IDList.Builder.class);
  }

  public static final int I_D_LIST_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.ids.AnyID> iDList_;
  /**
   * <code>repeated .ids.AnyID i_d_list = 1 [json_name = "iDList"];</code>
   */
  @java.lang.Override
  public java.util.List<com.ids.AnyID> getIDListList() {
    return iDList_;
  }
  /**
   * <code>repeated .ids.AnyID i_d_list = 1 [json_name = "iDList"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.ids.AnyIDOrBuilder> 
      getIDListOrBuilderList() {
    return iDList_;
  }
  /**
   * <code>repeated .ids.AnyID i_d_list = 1 [json_name = "iDList"];</code>
   */
  @java.lang.Override
  public int getIDListCount() {
    return iDList_.size();
  }
  /**
   * <code>repeated .ids.AnyID i_d_list = 1 [json_name = "iDList"];</code>
   */
  @java.lang.Override
  public com.ids.AnyID getIDList(int index) {
    return iDList_.get(index);
  }
  /**
   * <code>repeated .ids.AnyID i_d_list = 1 [json_name = "iDList"];</code>
   */
  @java.lang.Override
  public com.ids.AnyIDOrBuilder getIDListOrBuilder(
      int index) {
    return iDList_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < iDList_.size(); i++) {
      output.writeMessage(1, iDList_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < iDList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, iDList_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.lists.IDList)) {
      return super.equals(obj);
    }
    com.lists.IDList other = (com.lists.IDList) obj;

    if (!getIDListList()
        .equals(other.getIDListList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getIDListCount() > 0) {
      hash = (37 * hash) + I_D_LIST_FIELD_NUMBER;
      hash = (53 * hash) + getIDListList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.lists.IDList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lists.IDList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lists.IDList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lists.IDList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lists.IDList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lists.IDList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lists.IDList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lists.IDList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lists.IDList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.lists.IDList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lists.IDList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lists.IDList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.lists.IDList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code lists.IDList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:lists.IDList)
      com.lists.IDListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lists.IdListV1Proto.internal_static_lists_IDList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lists.IdListV1Proto.internal_static_lists_IDList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lists.IDList.class, com.lists.IDList.Builder.class);
    }

    // Construct using com.lists.IDList.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (iDListBuilder_ == null) {
        iDList_ = java.util.Collections.emptyList();
      } else {
        iDList_ = null;
        iDListBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.lists.IdListV1Proto.internal_static_lists_IDList_descriptor;
    }

    @java.lang.Override
    public com.lists.IDList getDefaultInstanceForType() {
      return com.lists.IDList.getDefaultInstance();
    }

    @java.lang.Override
    public com.lists.IDList build() {
      com.lists.IDList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.lists.IDList buildPartial() {
      com.lists.IDList result = new com.lists.IDList(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.lists.IDList result) {
      if (iDListBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          iDList_ = java.util.Collections.unmodifiableList(iDList_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.iDList_ = iDList_;
      } else {
        result.iDList_ = iDListBuilder_.build();
      }
    }

    private void buildPartial0(com.lists.IDList result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.lists.IDList) {
        return mergeFrom((com.lists.IDList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.lists.IDList other) {
      if (other == com.lists.IDList.getDefaultInstance()) return this;
      if (iDListBuilder_ == null) {
        if (!other.iDList_.isEmpty()) {
          if (iDList_.isEmpty()) {
            iDList_ = other.iDList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureIDListIsMutable();
            iDList_.addAll(other.iDList_);
          }
          onChanged();
        }
      } else {
        if (!other.iDList_.isEmpty()) {
          if (iDListBuilder_.isEmpty()) {
            iDListBuilder_.dispose();
            iDListBuilder_ = null;
            iDList_ = other.iDList_;
            bitField0_ = (bitField0_ & ~0x00000001);
            iDListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getIDListFieldBuilder() : null;
          } else {
            iDListBuilder_.addAllMessages(other.iDList_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.ids.AnyID m =
                  input.readMessage(
                      com.ids.AnyID.parser(),
                      extensionRegistry);
              if (iDListBuilder_ == null) {
                ensureIDListIsMutable();
                iDList_.add(m);
              } else {
                iDListBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.ids.AnyID> iDList_ =
      java.util.Collections.emptyList();
    private void ensureIDListIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        iDList_ = new java.util.ArrayList<com.ids.AnyID>(iDList_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ids.AnyID, com.ids.AnyID.Builder, com.ids.AnyIDOrBuilder> iDListBuilder_;

    /**
     * <code>repeated .ids.AnyID i_d_list = 1 [json_name = "iDList"];</code>
     */
    public java.util.List<com.ids.AnyID> getIDListList() {
      if (iDListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(iDList_);
      } else {
        return iDListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .ids.AnyID i_d_list = 1 [json_name = "iDList"];</code>
     */
    public int getIDListCount() {
      if (iDListBuilder_ == null) {
        return iDList_.size();
      } else {
        return iDListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .ids.AnyID i_d_list = 1 [json_name = "iDList"];</code>
     */
    public com.ids.AnyID getIDList(int index) {
      if (iDListBuilder_ == null) {
        return iDList_.get(index);
      } else {
        return iDListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .ids.AnyID i_d_list = 1 [json_name = "iDList"];</code>
     */
    public Builder setIDList(
        int index, com.ids.AnyID value) {
      if (iDListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIDListIsMutable();
        iDList_.set(index, value);
        onChanged();
      } else {
        iDListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ids.AnyID i_d_list = 1 [json_name = "iDList"];</code>
     */
    public Builder setIDList(
        int index, com.ids.AnyID.Builder builderForValue) {
      if (iDListBuilder_ == null) {
        ensureIDListIsMutable();
        iDList_.set(index, builderForValue.build());
        onChanged();
      } else {
        iDListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ids.AnyID i_d_list = 1 [json_name = "iDList"];</code>
     */
    public Builder addIDList(com.ids.AnyID value) {
      if (iDListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIDListIsMutable();
        iDList_.add(value);
        onChanged();
      } else {
        iDListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .ids.AnyID i_d_list = 1 [json_name = "iDList"];</code>
     */
    public Builder addIDList(
        int index, com.ids.AnyID value) {
      if (iDListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIDListIsMutable();
        iDList_.add(index, value);
        onChanged();
      } else {
        iDListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .ids.AnyID i_d_list = 1 [json_name = "iDList"];</code>
     */
    public Builder addIDList(
        com.ids.AnyID.Builder builderForValue) {
      if (iDListBuilder_ == null) {
        ensureIDListIsMutable();
        iDList_.add(builderForValue.build());
        onChanged();
      } else {
        iDListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ids.AnyID i_d_list = 1 [json_name = "iDList"];</code>
     */
    public Builder addIDList(
        int index, com.ids.AnyID.Builder builderForValue) {
      if (iDListBuilder_ == null) {
        ensureIDListIsMutable();
        iDList_.add(index, builderForValue.build());
        onChanged();
      } else {
        iDListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .ids.AnyID i_d_list = 1 [json_name = "iDList"];</code>
     */
    public Builder addAllIDList(
        java.lang.Iterable<? extends com.ids.AnyID> values) {
      if (iDListBuilder_ == null) {
        ensureIDListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, iDList_);
        onChanged();
      } else {
        iDListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .ids.AnyID i_d_list = 1 [json_name = "iDList"];</code>
     */
    public Builder clearIDList() {
      if (iDListBuilder_ == null) {
        iDList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        iDListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .ids.AnyID i_d_list = 1 [json_name = "iDList"];</code>
     */
    public Builder removeIDList(int index) {
      if (iDListBuilder_ == null) {
        ensureIDListIsMutable();
        iDList_.remove(index);
        onChanged();
      } else {
        iDListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .ids.AnyID i_d_list = 1 [json_name = "iDList"];</code>
     */
    public com.ids.AnyID.Builder getIDListBuilder(
        int index) {
      return getIDListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .ids.AnyID i_d_list = 1 [json_name = "iDList"];</code>
     */
    public com.ids.AnyIDOrBuilder getIDListOrBuilder(
        int index) {
      if (iDListBuilder_ == null) {
        return iDList_.get(index);  } else {
        return iDListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .ids.AnyID i_d_list = 1 [json_name = "iDList"];</code>
     */
    public java.util.List<? extends com.ids.AnyIDOrBuilder> 
         getIDListOrBuilderList() {
      if (iDListBuilder_ != null) {
        return iDListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(iDList_);
      }
    }
    /**
     * <code>repeated .ids.AnyID i_d_list = 1 [json_name = "iDList"];</code>
     */
    public com.ids.AnyID.Builder addIDListBuilder() {
      return getIDListFieldBuilder().addBuilder(
          com.ids.AnyID.getDefaultInstance());
    }
    /**
     * <code>repeated .ids.AnyID i_d_list = 1 [json_name = "iDList"];</code>
     */
    public com.ids.AnyID.Builder addIDListBuilder(
        int index) {
      return getIDListFieldBuilder().addBuilder(
          index, com.ids.AnyID.getDefaultInstance());
    }
    /**
     * <code>repeated .ids.AnyID i_d_list = 1 [json_name = "iDList"];</code>
     */
    public java.util.List<com.ids.AnyID.Builder> 
         getIDListBuilderList() {
      return getIDListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ids.AnyID, com.ids.AnyID.Builder, com.ids.AnyIDOrBuilder> 
        getIDListFieldBuilder() {
      if (iDListBuilder_ == null) {
        iDListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.ids.AnyID, com.ids.AnyID.Builder, com.ids.AnyIDOrBuilder>(
                iDList_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        iDList_ = null;
      }
      return iDListBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:lists.IDList)
  }

  // @@protoc_insertion_point(class_scope:lists.IDList)
  private static final com.lists.IDList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.lists.IDList();
  }

  public static com.lists.IDList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<IDList>
      PARSER = new com.google.protobuf.AbstractParser<IDList>() {
    @java.lang.Override
    public IDList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<IDList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<IDList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.lists.IDList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

