// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema/lists/base/propertyList.v1.proto

package com.lists;

public interface PropertyListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lists.PropertyList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .properties.AnyProperty property_list = 1 [json_name = "propertyList"];</code>
   */
  java.util.List<com.properties.AnyProperty> 
      getPropertyListList();
  /**
   * <code>repeated .properties.AnyProperty property_list = 1 [json_name = "propertyList"];</code>
   */
  com.properties.AnyProperty getPropertyList(int index);
  /**
   * <code>repeated .properties.AnyProperty property_list = 1 [json_name = "propertyList"];</code>
   */
  int getPropertyListCount();
  /**
   * <code>repeated .properties.AnyProperty property_list = 1 [json_name = "propertyList"];</code>
   */
  java.util.List<? extends com.properties.AnyPropertyOrBuilder> 
      getPropertyListOrBuilderList();
  /**
   * <code>repeated .properties.AnyProperty property_list = 1 [json_name = "propertyList"];</code>
   */
  com.properties.AnyPropertyOrBuilder getPropertyListOrBuilder(
      int index);
}
