// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/genesis/genesis.v1.proto

package com.identities;

public interface GenesisOrBuilder extends
    // @@protoc_insertion_point(interface_extends:identities.Genesis)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .identities.Mappable mappables = 1 [json_name = "mappables"];</code>
   */
  java.util.List<com.identities.Mappable> 
      getMappablesList();
  /**
   * <code>repeated .identities.Mappable mappables = 1 [json_name = "mappables"];</code>
   */
  com.identities.Mappable getMappables(int index);
  /**
   * <code>repeated .identities.Mappable mappables = 1 [json_name = "mappables"];</code>
   */
  int getMappablesCount();
  /**
   * <code>repeated .identities.Mappable mappables = 1 [json_name = "mappables"];</code>
   */
  java.util.List<? extends com.identities.MappableOrBuilder> 
      getMappablesOrBuilderList();
  /**
   * <code>repeated .identities.Mappable mappables = 1 [json_name = "mappables"];</code>
   */
  com.identities.MappableOrBuilder getMappablesOrBuilder(
      int index);

  /**
   * <code>.parameters.ParameterList parameterList = 2 [json_name = "parameterList"];</code>
   * @return Whether the parameterList field is set.
   */
  boolean hasParameterList();
  /**
   * <code>.parameters.ParameterList parameterList = 2 [json_name = "parameterList"];</code>
   * @return The parameterList.
   */
  com.parameters.ParameterList getParameterList();
  /**
   * <code>.parameters.ParameterList parameterList = 2 [json_name = "parameterList"];</code>
   */
  com.parameters.ParameterListOrBuilder getParameterListOrBuilder();
}
