// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/assets/internal/transactions/mint/message.v1.proto

package com.assets.transactions.mint;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:assets.transactions.mint.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string from = 1 [json_name = "from"];</code>
   * @return The from.
   */
  java.lang.String getFrom();
  /**
   * <code>string from = 1 [json_name = "from"];</code>
   * @return The bytes for from.
   */
  com.google.protobuf.ByteString
      getFromBytes();

  /**
   * <code>.ids.IdentityID from_i_d = 2 [json_name = "fromID"];</code>
   * @return Whether the fromID field is set.
   */
  boolean hasFromID();
  /**
   * <code>.ids.IdentityID from_i_d = 2 [json_name = "fromID"];</code>
   * @return The fromID.
   */
  com.ids.IdentityID getFromID();
  /**
   * <code>.ids.IdentityID from_i_d = 2 [json_name = "fromID"];</code>
   */
  com.ids.IdentityIDOrBuilder getFromIDOrBuilder();

  /**
   * <code>.ids.IdentityID to_i_d = 3 [json_name = "toID"];</code>
   * @return Whether the toID field is set.
   */
  boolean hasToID();
  /**
   * <code>.ids.IdentityID to_i_d = 3 [json_name = "toID"];</code>
   * @return The toID.
   */
  com.ids.IdentityID getToID();
  /**
   * <code>.ids.IdentityID to_i_d = 3 [json_name = "toID"];</code>
   */
  com.ids.IdentityIDOrBuilder getToIDOrBuilder();

  /**
   * <code>.ids.ClassificationID classification_i_d = 4 [json_name = "classificationID"];</code>
   * @return Whether the classificationID field is set.
   */
  boolean hasClassificationID();
  /**
   * <code>.ids.ClassificationID classification_i_d = 4 [json_name = "classificationID"];</code>
   * @return The classificationID.
   */
  com.ids.ClassificationID getClassificationID();
  /**
   * <code>.ids.ClassificationID classification_i_d = 4 [json_name = "classificationID"];</code>
   */
  com.ids.ClassificationIDOrBuilder getClassificationIDOrBuilder();

  /**
   * <code>.lists.PropertyList immutable_meta_properties = 5 [json_name = "immutableMetaProperties"];</code>
   * @return Whether the immutableMetaProperties field is set.
   */
  boolean hasImmutableMetaProperties();
  /**
   * <code>.lists.PropertyList immutable_meta_properties = 5 [json_name = "immutableMetaProperties"];</code>
   * @return The immutableMetaProperties.
   */
  com.lists.PropertyList getImmutableMetaProperties();
  /**
   * <code>.lists.PropertyList immutable_meta_properties = 5 [json_name = "immutableMetaProperties"];</code>
   */
  com.lists.PropertyListOrBuilder getImmutableMetaPropertiesOrBuilder();

  /**
   * <code>.lists.PropertyList immutable_properties = 6 [json_name = "immutableProperties"];</code>
   * @return Whether the immutableProperties field is set.
   */
  boolean hasImmutableProperties();
  /**
   * <code>.lists.PropertyList immutable_properties = 6 [json_name = "immutableProperties"];</code>
   * @return The immutableProperties.
   */
  com.lists.PropertyList getImmutableProperties();
  /**
   * <code>.lists.PropertyList immutable_properties = 6 [json_name = "immutableProperties"];</code>
   */
  com.lists.PropertyListOrBuilder getImmutablePropertiesOrBuilder();

  /**
   * <code>.lists.PropertyList mutable_meta_properties = 7 [json_name = "mutableMetaProperties"];</code>
   * @return Whether the mutableMetaProperties field is set.
   */
  boolean hasMutableMetaProperties();
  /**
   * <code>.lists.PropertyList mutable_meta_properties = 7 [json_name = "mutableMetaProperties"];</code>
   * @return The mutableMetaProperties.
   */
  com.lists.PropertyList getMutableMetaProperties();
  /**
   * <code>.lists.PropertyList mutable_meta_properties = 7 [json_name = "mutableMetaProperties"];</code>
   */
  com.lists.PropertyListOrBuilder getMutableMetaPropertiesOrBuilder();

  /**
   * <code>.lists.PropertyList mutable_properties = 8 [json_name = "mutableProperties"];</code>
   * @return Whether the mutableProperties field is set.
   */
  boolean hasMutableProperties();
  /**
   * <code>.lists.PropertyList mutable_properties = 8 [json_name = "mutableProperties"];</code>
   * @return The mutableProperties.
   */
  com.lists.PropertyList getMutableProperties();
  /**
   * <code>.lists.PropertyList mutable_properties = 8 [json_name = "mutableProperties"];</code>
   */
  com.lists.PropertyListOrBuilder getMutablePropertiesOrBuilder();
}
