// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/orders/internal/transactions/make/response.v1.proto

package com.orders.transactions.make;

public final class ResponseV1Proto {
  private ResponseV1Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orders_transactions_make_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orders_transactions_make_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n;modules/orders/internal/transactions/m" +
      "ake/response.v1.proto\022\030orders.transactio" +
      "ns.make\"\n\n\010ResponseB\373\001\n\034com.orders.trans" +
      "actions.makeB\017ResponseV1ProtoP\001ZHgithub." +
      "com/AssetMantle/modules/modules/orders/i" +
      "nternal/transactions/make\242\002\003OTM\252\002\030Orders" +
      ".Transactions.Make\312\002\030Orders\\Transactions" +
      "\\Make\342\002$Orders\\Transactions\\Make\\GPBMeta" +
      "data\352\002\032Orders::Transactions::Makeb\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_orders_transactions_make_Response_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_orders_transactions_make_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orders_transactions_make_Response_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
