// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/orders/internal/transactions/make/transactionResponse.v1.proto

package com.orders.transactions.make;

public interface TransactionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:orders.transactions.make.TransactionResponse)
    com.google.protobuf.MessageOrBuilder {
}
