// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: assets/queries/assets/service.proto

package com.assetmantle.modules.assets.queries.assets;

public final class ServiceProto {
  private ServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#assets/queries/assets/service.proto\022)a" +
      "ssetmantle.modules.assets.queries.assets" +
      "\032\034google/api/annotations.proto\032)assets/q" +
      "ueries/assets/query_request.proto\032*asset" +
      "s/queries/assets/query_response.proto2\256\001" +
      "\n\007Service\022\242\001\n\006Handle\0227.assetmantle.modul" +
      "es.assets.queries.assets.QueryRequest\0328." +
      "assetmantle.modules.assets.queries.asset" +
      "s.QueryResponse\"%\202\323\344\223\002\037\022\035/mantle/assets/" +
      "v1beta1/assetsB\277\002\n-com.assetmantle.modul" +
      "es.assets.queries.assetsB\014ServiceProtoP\001" +
      "Z6github.com/AssetMantle/modules/x/asset" +
      "s/queries/assets\242\002\005AMAQA\252\002)Assetmantle.M" +
      "odules.Assets.Queries.Assets\312\002)Assetmant" +
      "le\\Modules\\Assets\\Queries\\Assets\342\0025Asset" +
      "mantle\\Modules\\Assets\\Queries\\Assets\\GPB" +
      "Metadata\352\002-Assetmantle::Modules::Assets:" +
      ":Queries::Assetsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.assetmantle.modules.assets.queries.assets.QueryRequestProto.getDescriptor(),
          com.assetmantle.modules.assets.queries.assets.QueryResponseProto.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.assetmantle.modules.assets.queries.assets.QueryRequestProto.getDescriptor();
    com.assetmantle.modules.assets.queries.assets.QueryResponseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
