// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: identities/transactions/define/transaction_response.proto

package com.assetmantle.modules.identities.transactions.define;

public interface TransactionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:assetmantle.modules.identities.transactions.define.TransactionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string classification_i_d = 1 [json_name = "classificationID"];</code>
   * @return The classificationID.
   */
  java.lang.String getClassificationID();
  /**
   * <code>string classification_i_d = 1 [json_name = "classificationID"];</code>
   * @return The bytes for classificationID.
   */
  com.google.protobuf.ByteString
      getClassificationIDBytes();
}
