// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: identities/transactions/define/transaction_response.proto

package com.assetmantle.modules.identities.transactions.define;

public final class TransactionResponseProto {
  private TransactionResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_assetmantle_modules_identities_transactions_define_TransactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_assetmantle_modules_identities_transactions_define_TransactionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n9identities/transactions/define/transac" +
      "tion_response.proto\0222assetmantle.modules" +
      ".identities.transactions.define\"C\n\023Trans" +
      "actionResponse\022,\n\022classification_i_d\030\001 \001" +
      "(\tR\020classificationIDB\201\003\n6com.assetmantle" +
      ".modules.identities.transactions.defineB" +
      "\030TransactionResponseProtoP\001Z?github.com/" +
      "AssetMantle/modules/x/identities/transac" +
      "tions/define\242\002\005AMITD\252\0022Assetmantle.Modul" +
      "es.Identities.Transactions.Define\312\0022Asse" +
      "tmantle\\Modules\\Identities\\Transactions\\" +
      "Define\342\002>Assetmantle\\Modules\\Identities\\" +
      "Transactions\\Define\\GPBMetadata\352\0026Assetm" +
      "antle::Modules::Identities::Transactions" +
      "::Defineb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_assetmantle_modules_identities_transactions_define_TransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_assetmantle_modules_identities_transactions_define_TransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_assetmantle_modules_identities_transactions_define_TransactionResponse_descriptor,
        new java.lang.String[] { "ClassificationID", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
