// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: data/base/any_listable_data.proto

package com.assetmantle.schema.data.base;

public final class AnyListableDataProto {
  private AnyListableDataProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_assetmantle_schema_data_base_AnyListableData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_assetmantle_schema_data_base_AnyListableData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!data/base/any_listable_data.proto\022\034ass" +
      "etmantle.schema.data.base\032 data/base/acc" +
      "_address_data.proto\032\034data/base/boolean_d" +
      "ata.proto\032\030data/base/dec_data.proto\032\033dat" +
      "a/base/height_data.proto\032\027data/base/id_d" +
      "ata.proto\032\033data/base/number_data.proto\032\033" +
      "data/base/string_data.proto\032\024gogoproto/g" +
      "ogo.proto\"\266\004\n\017AnyListableData\022X\n\020acc_add" +
      "ress_data\030\001 \001(\0132,.assetmantle.schema.dat" +
      "a.base.AccAddressDataH\000R\016accAddressData\022" +
      "N\n\014boolean_data\030\002 \001(\0132).assetmantle.sche" +
      "ma.data.base.BooleanDataH\000R\013booleanData\022" +
      "B\n\010dec_data\030\003 \001(\0132%.assetmantle.schema.d" +
      "ata.base.DecDataH\000R\007decData\022K\n\013height_da" +
      "ta\030\004 \001(\0132(.assetmantle.schema.data.base." +
      "HeightDataH\000R\nheightData\022@\n\010i_d_data\030\005 \001" +
      "(\0132$.assetmantle.schema.data.base.IDData" +
      "H\000R\006iDData\022K\n\013number_data\030\006 \001(\0132(.assetm" +
      "antle.schema.data.base.NumberDataH\000R\nnum" +
      "berData\022K\n\013string_data\030\007 \001(\0132(.assetmant" +
      "le.schema.data.base.StringDataH\000R\nstring" +
      "Data:\004\210\240\037\000B\006\n\004implB\370\001\n com.assetmantle.s" +
      "chema.data.baseB\024AnyListableDataProtoP\001Z" +
      "*github.com/AssetMantle/schema/go/data/b" +
      "ase\242\002\004ASDB\252\002\034Assetmantle.Schema.Data.Bas" +
      "e\312\002\034Assetmantle\\Schema\\Data\\Base\342\002(Asset" +
      "mantle\\Schema\\Data\\Base\\GPBMetadata\352\002\037As" +
      "setmantle::Schema::Data::Baseb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.assetmantle.schema.data.base.AccAddressDataProto.getDescriptor(),
          com.assetmantle.schema.data.base.BooleanDataProto.getDescriptor(),
          com.assetmantle.schema.data.base.DecDataProto.getDescriptor(),
          com.assetmantle.schema.data.base.HeightDataProto.getDescriptor(),
          com.assetmantle.schema.data.base.IdDataProto.getDescriptor(),
          com.assetmantle.schema.data.base.NumberDataProto.getDescriptor(),
          com.assetmantle.schema.data.base.StringDataProto.getDescriptor(),
          com.gogoproto.GogoProto.getDescriptor(),
        });
    internal_static_assetmantle_schema_data_base_AnyListableData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_assetmantle_schema_data_base_AnyListableData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_assetmantle_schema_data_base_AnyListableData_descriptor,
        new java.lang.String[] { "AccAddressData", "BooleanData", "DecData", "HeightData", "IDData", "NumberData", "StringData", "Impl", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.goprotoGetters);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.assetmantle.schema.data.base.AccAddressDataProto.getDescriptor();
    com.assetmantle.schema.data.base.BooleanDataProto.getDescriptor();
    com.assetmantle.schema.data.base.DecDataProto.getDescriptor();
    com.assetmantle.schema.data.base.HeightDataProto.getDescriptor();
    com.assetmantle.schema.data.base.IdDataProto.getDescriptor();
    com.assetmantle.schema.data.base.NumberDataProto.getDescriptor();
    com.assetmantle.schema.data.base.StringDataProto.getDescriptor();
    com.gogoproto.GogoProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
