// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/orders/internal/transactions/revoke/response.v1.proto

package com.orders.transactions.revoke;

public final class ResponseV1Proto {
  private ResponseV1Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orders_transactions_revoke_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orders_transactions_revoke_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n=modules/orders/internal/transactions/r" +
      "evoke/response.v1.proto\022\032orders.transact" +
      "ions.revoke\"\n\n\010ResponseB\207\002\n\036com.orders.t" +
      "ransactions.revokeB\017ResponseV1ProtoP\001ZJg" +
      "ithub.com/AssetMantle/modules/modules/or" +
      "ders/internal/transactions/revoke\242\002\003OTR\252" +
      "\002\032Orders.Transactions.Revoke\312\002\032Orders\\Tr" +
      "ansactions\\Revoke\342\002&Orders\\Transactions\\" +
      "Revoke\\GPBMetadata\352\002\034Orders::Transaction" +
      "s::Revokeb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_orders_transactions_revoke_Response_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_orders_transactions_revoke_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orders_transactions_revoke_Response_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
