// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/transactions/provision/transactionResponse.v1.proto

package com.identities.transactions.provision;

public interface TransactionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:identities.transactions.provision.TransactionResponse)
    com.google.protobuf.MessageOrBuilder {
}
