package constants

object Actor {

  val PRIMARY_ACTOR = "PRIMARY_ACTOR"

  val ACTOR_NOT_FOUND = "ACTOR_NOT_FOUND"
  val ACTOR_NOT_FOUND_FOR_SHUTDOWN = "ACTOR_NOT_FOUND_FOR_SHUTDOWN"

  val ACTOR_PUSH_NOTIFICATION = "ACTOR_PUSH_NOTIFICATION"


}
