package constants

object Module {
  val HOME_CONTROLLER = "HOME_CONTROLLER"
  val ACCOUNT_CONTROLLER = "ACCOUNT_CONTROLLER"
  val COLLECTION_CONTROLLER = "COLLECTION_CONTROLLER"
  val NFT_CONTROLLER = "NFT_CONTROLLER"

  val MASTER_ACCOUNT = "MASTER_ACCOUNT"
  val MASTER_COLLECTION = "MASTER_COLLECTION"
  val MASTER_COLLECTION_FILE = "MASTER_COLLECTION_FILE"
  val MASTER_NFT = "MASTER_NFT"
  val MASTER_WALLET = "MASTER_WALLET"
  val MASTER_KEY = "MASTER_KEY"

  val BLOCKCHAIN_ACCOUNT = "BLOCKCHAIN_ACCOUNT"
  val BLOCKCHAIN_TRANSACTION = "BLOCKCHAIN_TRANSACTION"

  val BLOCKCHAIN_TRANSACTION_SEND_COIN = "BLOCKCHAIN_TRANSACTION_SEND_COIN"

  val MASTER_TRANSACTION_SESSION_TOKEN = "MASTER_TRANSACTION_SESSION_TOKEN"
  val MASTER_TRANSACTION_PUSH_NOTIFICATION_TOKEN = "MASTER_TRANSACTION_PUSH_NOTIFICATION_TOKEN"

  val STARTER_SERVICE = "STARTER_SERVICE"

  val UTILITIES_BECH32 = "UTILITIES_BECH32"
  val UTILITIES_WALLET = "UTILITIES_WALLET"
  val UTILITIES_IPFS = "UTILITIES_IPFS"
  val UTILITIES_AMAZON_S3 = "UTILITIES_AMAZON_S3"
  val UTILITIES_FILE_OPERATIONS = "UTILITIES_FILE_OPERATIONS"
  val UTILITIES_FILE_RESOURCE_MANAGER = "UTILITIES_FILE_RESOURCE_MANAGER"
  val UTILITIES_IMAGE_PROCESS = "UTILITIES_IMAGE_PROCESS"
  val UTILITIES_MICRO_NUMBER = "UTILITIES_MICRO_NUMBER"
  val UTILITIES_DATE = "UTILITIES_DATE"
  val UTILITIES_BLOCKCHAIN = "UTILITIES_BLOCKCHAIN"
  val UTILITIES_SECRETS = "UTILITIES_SECRETS"

  val ACTIONS_WITH_LOGIN_ACTION = "ACTIONS_WITH_LOGIN_ACTION"
  val ACTIONS_WITHOUT_LOGIN_ACTION_ASYNC = "ACTIONS_WITHOUT_LOGIN_ACTION_ASYNC"

  val PUBLIC_KEYS = "PUBLIC_KEYS"
  val COMMON_TRANSACTION_MESSAGE = "COMMON_TRANSACTION_MESSAGE"
  val TRANSACTION_MESSAGE_AUTHZ = "TRANSACTION_MESSAGE_AUTHZ"
  val PROPOSAL_CONTENT = "PROPOSAL_CONTENT"
  val COIN = "COIN"
  val FEE_GRANT = "FEE_GRANT"
}
