package constants

object Module {
  val HOME_CONTROLLER = "HOME_CONTROLLER"
  val ACCOUNT_CONTROLLER = "ACCOUNT_CONTROLLER"

  val MASTER_ACCOUNT = "MASTER_ACCOUNT"

  val UTILITIES_BECH32 = "UTILITIES_BECH32"
  val UTILITIES_WALLET = "UTILITIES_WALLET"
}
