package constants

object Module {
  val HOME_CONTROLLER = "HOME_CONTROLLER"
  val ACCOUNT_CONTROLLER = "ACCOUNT_CONTROLLER"

  val MASTER_ACCOUNT = "MASTER_ACCOUNT"

  val UTILITIES_BECH32 = "UTILITIES_BECH32"
  val UTILITIES_WALLET = "UTILITIES_WALLET"
  val UTILITIES_IPFS = "UTILITIES_IPFS"
  val UTILITIES_AMAZON_S3 = "UTILITIES_AMAZON_S3"
  val UTILITIES_FILE_OPERATIONS = "UTILITIES_FILE_OPERATIONS"
  val UTILITIES_FILE_RESOURCE_MANAGER = "UTILITIES_FILE_RESOURCE_MANAGER"
  val UTILITIES_IMAGE_PROCESS = "UTILITIES_IMAGE_PROCESS"
}
