// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/assets/internal/transactions/mutate/transactionResponse.v1.proto

package com.assets.transactions.mutate;

public interface TransactionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:assets.transactions.mutate.TransactionResponse)
    com.google.protobuf.MessageOrBuilder {
}
