// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: identities/transactions/quash/service.proto

package com.assetmantle.modules.identities.transactions.quash;

public final class ServiceProto {
  private ServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n+identities/transactions/quash/service." +
      "proto\0221assetmantle.modules.identities.tr" +
      "ansactions.quash\032\034google/api/annotations" +
      ".proto\032+identities/transactions/quash/me" +
      "ssage.proto\0328identities/transactions/qua" +
      "sh/transaction_response.proto2\272\001\n\007Servic" +
      "e\022\256\001\n\006Handle\022:.assetmantle.modules.ident" +
      "ities.transactions.quash.Message\032F.asset" +
      "mantle.modules.identities.transactions.q" +
      "uash.TransactionResponse\" \202\323\344\223\002\032\"\030/mantl" +
      "e/identities/quashB\357\002\n5com.assetmantle.m" +
      "odules.identities.transactions.quashB\014Se" +
      "rviceProtoP\001Z>github.com/AssetMantle/mod" +
      "ules/x/identities/transactions/quash\242\002\005A" +
      "MITQ\252\0021Assetmantle.Modules.Identities.Tr" +
      "ansactions.Quash\312\0021Assetmantle\\Modules\\I" +
      "dentities\\Transactions\\Quash\342\002=Assetmant" +
      "le\\Modules\\Identities\\Transactions\\Quash" +
      "\\GPBMetadata\352\0025Assetmantle::Modules::Ide" +
      "ntities::Transactions::Quashb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.assetmantle.modules.identities.transactions.quash.MessageProto.getDescriptor(),
          com.assetmantle.modules.identities.transactions.quash.TransactionResponseProto.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.assetmantle.modules.identities.transactions.quash.MessageProto.getDescriptor();
    com.assetmantle.modules.identities.transactions.quash.TransactionResponseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
