// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/transactions/issue/message.v1.proto

package com.identities.transactions.issue;

public final class MessageV1Proto {
  private MessageV1Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_identities_transactions_issue_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_identities_transactions_issue_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n?modules/identities/internal/transactio" +
      "ns/issue/message.v1.proto\022\035identities.tr" +
      "ansactions.issue\032)schema/ids/base/classi" +
      "ficationID.v1.proto\032#schema/ids/base/ide" +
      "ntityID.v1.proto\032\'schema/lists/base/prop" +
      "ertyList.v1.proto\"\307\003\n\007Message\022\022\n\004from\030\001 " +
      "\001(\tR\004from\022)\n\010from_i_d\030\002 \001(\0132\017.ids.Identi" +
      "tyIDR\006fromID\022\016\n\002to\030\003 \001(\tR\002to\022C\n\022classifi" +
      "cation_i_d\030\004 \001(\0132\025.ids.ClassificationIDR" +
      "\020classificationID\022O\n\031immutable_meta_prop" +
      "erties\030\005 \001(\0132\023.lists.PropertyListR\027immut" +
      "ableMetaProperties\022F\n\024immutable_properti" +
      "es\030\006 \001(\0132\023.lists.PropertyListR\023immutable" +
      "Properties\022K\n\027mutable_meta_properties\030\007 " +
      "\001(\0132\023.lists.PropertyListR\025mutableMetaPro" +
      "perties\022B\n\022mutable_properties\030\010 \001(\0132\023.li" +
      "sts.PropertyListR\021mutablePropertiesB\230\002\n!" +
      "com.identities.transactions.issueB\016Messa" +
      "geV1ProtoP\001ZMgithub.com/AssetMantle/modu" +
      "les/modules/identities/internal/transact" +
      "ions/issue\242\002\003ITI\252\002\035Identities.Transactio" +
      "ns.Issue\312\002\035Identities\\Transactions\\Issue" +
      "\342\002)Identities\\Transactions\\Issue\\GPBMeta" +
      "data\352\002\037Identities::Transactions::Issueb\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.ClassificationIDV1Proto.getDescriptor(),
          com.ids.IdentityIDV1Proto.getDescriptor(),
          com.lists.PropertyListV1Proto.getDescriptor(),
        });
    internal_static_identities_transactions_issue_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_identities_transactions_issue_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_identities_transactions_issue_Message_descriptor,
        new java.lang.String[] { "From", "FromID", "To", "ClassificationID", "ImmutableMetaProperties", "ImmutableProperties", "MutableMetaProperties", "MutableProperties", });
    com.ids.ClassificationIDV1Proto.getDescriptor();
    com.ids.IdentityIDV1Proto.getDescriptor();
    com.lists.PropertyListV1Proto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
