// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/transactions/issue/response.v1.proto

package com.identities.transactions.issue;

public final class ResponseV1Proto {
  private ResponseV1Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_identities_transactions_issue_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_identities_transactions_issue_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n@modules/identities/internal/transactio" +
      "ns/issue/response.v1.proto\022\035identities.t" +
      "ransactions.issue\"\n\n\010ResponseB\231\002\n!com.id" +
      "entities.transactions.issueB\017ResponseV1P" +
      "rotoP\001ZMgithub.com/AssetMantle/modules/m" +
      "odules/identities/internal/transactions/" +
      "issue\242\002\003ITI\252\002\035Identities.Transactions.Is" +
      "sue\312\002\035Identities\\Transactions\\Issue\342\002)Id" +
      "entities\\Transactions\\Issue\\GPBMetadata\352" +
      "\002\037Identities::Transactions::Issueb\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_identities_transactions_issue_Response_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_identities_transactions_issue_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_identities_transactions_issue_Response_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
