// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/transactions/quash/service.v1.proto

package com.identities.transactions.quash;

public final class ServiceV1Proto {
  private ServiceV1Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n?modules/identities/internal/transactio" +
      "ns/quash/service.v1.proto\022\035identities.tr" +
      "ansactions.quash\032\034google/api/annotations" +
      ".proto\032?modules/identities/internal/tran" +
      "sactions/quash/message.v1.proto\032Kmodules" +
      "/identities/internal/transactions/quash/" +
      "transactionResponse.v1.proto2\222\001\n\007Service" +
      "\022\206\001\n\006Handle\022&.identities.transactions.qu" +
      "ash.Message\0322.identities.transactions.qu" +
      "ash.TransactionResponse\" \202\323\344\223\002\032\"\030/mantle" +
      "/identities/quashB\230\002\n!com.identities.tra" +
      "nsactions.quashB\016ServiceV1ProtoP\001ZMgithu" +
      "b.com/AssetMantle/modules/modules/identi" +
      "ties/internal/transactions/quash\242\002\003ITQ\252\002" +
      "\035Identities.Transactions.Quash\312\002\035Identit" +
      "ies\\Transactions\\Quash\342\002)Identities\\Tran" +
      "sactions\\Quash\\GPBMetadata\352\002\037Identities:" +
      ":Transactions::Quashb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.identities.transactions.quash.MessageV1Proto.getDescriptor(),
          com.identities.transactions.quash.TransactionResponseV1Proto.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.identities.transactions.quash.MessageV1Proto.getDescriptor();
    com.identities.transactions.quash.TransactionResponseV1Proto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
