// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/assets/internal/transactions/renumerate/response.v1.proto

package com.assets.transactions.renumerate;

public final class ResponseV1Proto {
  private ResponseV1Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_assets_transactions_renumerate_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_assets_transactions_renumerate_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nAmodules/assets/internal/transactions/r" +
      "enumerate/response.v1.proto\022\036assets.tran" +
      "sactions.renumerate\"\n\n\010ResponseB\237\002\n\"com." +
      "assets.transactions.renumerateB\017Response" +
      "V1ProtoP\001ZNgithub.com/AssetMantle/module" +
      "s/modules/assets/internal/transactions/r" +
      "enumerate\242\002\003ATR\252\002\036Assets.Transactions.Re" +
      "numerate\312\002\036Assets\\Transactions\\Renumerat" +
      "e\342\002*Assets\\Transactions\\Renumerate\\GPBMe" +
      "tadata\352\002 Assets::Transactions::Renumerat" +
      "eb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_assets_transactions_renumerate_Response_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_assets_transactions_renumerate_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_assets_transactions_renumerate_Response_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
