// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/orders/internal/transactions/deputize/transactionResponse.v1.proto

package com.orders.transactions.deputize;

public final class TransactionResponseV1Proto {
  private TransactionResponseV1Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orders_transactions_deputize_TransactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orders_transactions_deputize_TransactionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nJmodules/orders/internal/transactions/d" +
      "eputize/transactionResponse.v1.proto\022\034or" +
      "ders.transactions.deputize\"\025\n\023Transactio" +
      "nResponseB\236\002\n com.orders.transactions.de" +
      "putizeB\032TransactionResponseV1ProtoP\001ZLgi" +
      "thub.com/AssetMantle/modules/modules/ord" +
      "ers/internal/transactions/deputize\242\002\003OTD" +
      "\252\002\034Orders.Transactions.Deputize\312\002\034Orders" +
      "\\Transactions\\Deputize\342\002(Orders\\Transact" +
      "ions\\Deputize\\GPBMetadata\352\002\036Orders::Tran" +
      "sactions::Deputizeb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_orders_transactions_deputize_TransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_orders_transactions_deputize_TransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orders_transactions_deputize_TransactionResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
