// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: utilities/test/schema/helpers/base/message.proto

package com.test;

public interface TestMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:test.TestMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes from = 1 [json_name = "from"];</code>
   * @return The from.
   */
  com.google.protobuf.ByteString getFrom();

  /**
   * <code>string i_d = 2 [json_name = "iD"];</code>
   * @return The iD.
   */
  java.lang.String getID();
  /**
   * <code>string i_d = 2 [json_name = "iD"];</code>
   * @return The bytes for iD.
   */
  com.google.protobuf.ByteString
      getIDBytes();
}
