// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/transactions/mutate/response.v1.proto

package com.identities.transactions.mutate;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:identities.transactions.mutate.Response)
    com.google.protobuf.MessageOrBuilder {
}
