// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/queries/identity/queryRequest.v1.proto

package com.identities.queries.identity;

public final class QueryRequestV1Proto {
  private QueryRequestV1Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_identities_queries_identity_QueryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_identities_queries_identity_QueryRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nBmodules/identities/internal/queries/id" +
      "entity/queryRequest.v1.proto\022\033identities" +
      ".queries.identity\032#schema/ids/base/ident" +
      "ityID.v1.proto\"A\n\014QueryRequest\0221\n\014identi" +
      "ty_i_d\030\001 \001(\0132\017.ids.IdentityIDR\nidentityI" +
      "DB\221\002\n\037com.identities.queries.identityB\023Q" +
      "ueryRequestV1ProtoP\001ZKgithub.com/AssetMa" +
      "ntle/modules/modules/identities/internal" +
      "/queries/identity\242\002\003IQI\252\002\033Identities.Que" +
      "ries.Identity\312\002\033Identities\\Queries\\Ident" +
      "ity\342\002\'Identities\\Queries\\Identity\\GPBMet" +
      "adata\352\002\035Identities::Queries::Identityb\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ids.IdentityIDV1Proto.getDescriptor(),
        });
    internal_static_identities_queries_identity_QueryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_identities_queries_identity_QueryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_identities_queries_identity_QueryRequest_descriptor,
        new java.lang.String[] { "IdentityID", });
    com.ids.IdentityIDV1Proto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
