// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/identities/internal/transactions/nub/response.v1.proto

package com.identities.transactions.nub;

public final class ResponseV1Proto {
  private ResponseV1Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_identities_transactions_nub_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_identities_transactions_nub_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n>modules/identities/internal/transactio" +
      "ns/nub/response.v1.proto\022\033identities.tra" +
      "nsactions.nub\"\n\n\010ResponseB\215\002\n\037com.identi" +
      "ties.transactions.nubB\017ResponseV1ProtoP\001" +
      "ZKgithub.com/AssetMantle/modules/modules" +
      "/identities/internal/transactions/nub\242\002\003" +
      "ITN\252\002\033Identities.Transactions.Nub\312\002\033Iden" +
      "tities\\Transactions\\Nub\342\002\'Identities\\Tra" +
      "nsactions\\Nub\\GPBMetadata\352\002\035Identities::" +
      "Transactions::Nubb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_identities_transactions_nub_Response_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_identities_transactions_nub_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_identities_transactions_nub_Response_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
