// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/metas/internal/genesis/genesisState.v1.proto

package com.metas;

public final class GenesisStateV1Proto {
  private GenesisStateV1Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_metas_GenesisState_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_metas_GenesisState_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n4modules/metas/internal/genesis/genesis" +
      "State.v1.proto\022\005metas\032\024gogoproto/gogo.pr" +
      "oto\0321modules/metas/internal/mappable/map" +
      "pable.v1.proto\032)schema/parameters/base/p" +
      "arameter.v1.proto\"z\n\014GenesisState\022-\n\tmap" +
      "pables\030\001 \003(\0132\017.metas.MappableR\tmappables" +
      "\0225\n\nparameters\030\002 \003(\0132\025.parameters.Parame" +
      "terR\nparameters:\004\210\240\037\000B\223\001\n\tcom.metasB\023Gen" +
      "esisStateV1ProtoP\001Z=github.com/AssetMant" +
      "le/modules/modules/metas/internal/genesi" +
      "s\242\002\003MXX\252\002\005Metas\312\002\005Metas\342\002\021Metas\\GPBMetad" +
      "ata\352\002\005Metasb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gogoproto.GogoProto.getDescriptor(),
          com.metas.MappableV1Proto.getDescriptor(),
          com.parameters.ParameterV1Proto.getDescriptor(),
        });
    internal_static_metas_GenesisState_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_metas_GenesisState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_metas_GenesisState_descriptor,
        new java.lang.String[] { "Mappables", "Parameters", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.goprotoGetters);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.gogoproto.GogoProto.getDescriptor();
    com.metas.MappableV1Proto.getDescriptor();
    com.parameters.ParameterV1Proto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
