// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/classifications/internal/genesis/genesis.v1.proto

package com.classifications;

public interface GenesisOrBuilder extends
    // @@protoc_insertion_point(interface_extends:classifications.Genesis)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .classifications.Mappable mappables = 1 [json_name = "mappables"];</code>
   */
  java.util.List<com.classifications.Mappable> 
      getMappablesList();
  /**
   * <code>repeated .classifications.Mappable mappables = 1 [json_name = "mappables"];</code>
   */
  com.classifications.Mappable getMappables(int index);
  /**
   * <code>repeated .classifications.Mappable mappables = 1 [json_name = "mappables"];</code>
   */
  int getMappablesCount();
  /**
   * <code>repeated .classifications.Mappable mappables = 1 [json_name = "mappables"];</code>
   */
  java.util.List<? extends com.classifications.MappableOrBuilder> 
      getMappablesOrBuilderList();
  /**
   * <code>repeated .classifications.Mappable mappables = 1 [json_name = "mappables"];</code>
   */
  com.classifications.MappableOrBuilder getMappablesOrBuilder(
      int index);

  /**
   * <code>repeated .parameters.Parameter parameters = 2 [json_name = "parameters"];</code>
   */
  java.util.List<com.parameters.Parameter> 
      getParametersList();
  /**
   * <code>repeated .parameters.Parameter parameters = 2 [json_name = "parameters"];</code>
   */
  com.parameters.Parameter getParameters(int index);
  /**
   * <code>repeated .parameters.Parameter parameters = 2 [json_name = "parameters"];</code>
   */
  int getParametersCount();
  /**
   * <code>repeated .parameters.Parameter parameters = 2 [json_name = "parameters"];</code>
   */
  java.util.List<? extends com.parameters.ParameterOrBuilder> 
      getParametersOrBuilderList();
  /**
   * <code>repeated .parameters.Parameter parameters = 2 [json_name = "parameters"];</code>
   */
  com.parameters.ParameterOrBuilder getParametersOrBuilder(
      int index);
}
