// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/classifications/internal/genesis/genesis.v1.proto

package com.classifications;

public final class GenesisV1Proto {
  private GenesisV1Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_classifications_Genesis_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_classifications_Genesis_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n9modules/classifications/internal/genes" +
      "is/genesis.v1.proto\022\017classifications\032\024go" +
      "goproto/gogo.proto\032;modules/classificati" +
      "ons/internal/mappable/mappable.v1.proto\032" +
      "-schema/parameters/base/parameterList.v1" +
      ".proto\"\211\001\n\007Genesis\0227\n\tmappables\030\001 \003(\0132\031." +
      "classifications.MappableR\tmappables\022?\n\rp" +
      "arameterList\030\002 \001(\0132\031.parameters.Paramete" +
      "rListR\rparameterList:\004\210\240\037\000B\312\001\n\023com.class" +
      "ificationsB\016GenesisV1ProtoP\001ZGgithub.com" +
      "/AssetMantle/modules/modules/classificat" +
      "ions/internal/genesis\242\002\003CXX\252\002\017Classifica" +
      "tions\312\002\017Classifications\342\002\033Classification" +
      "s\\GPBMetadata\352\002\017Classificationsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gogoproto.GogoProto.getDescriptor(),
          com.classifications.MappableV1Proto.getDescriptor(),
          com.parameters.ParameterListV1Proto.getDescriptor(),
        });
    internal_static_classifications_Genesis_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_classifications_Genesis_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_classifications_Genesis_descriptor,
        new java.lang.String[] { "Mappables", "ParameterList", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.gogoproto.GogoProto.goprotoGetters);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.gogoproto.GogoProto.getDescriptor();
    com.classifications.MappableV1Proto.getDescriptor();
    com.parameters.ParameterListV1Proto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
