// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/maintainers/internal/key/key.v1.proto

package com.maintainers;

public interface KeyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:maintainers.Key)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ids.MaintainerID maintainer_i_d = 1 [json_name = "maintainerID"];</code>
   * @return Whether the maintainerID field is set.
   */
  boolean hasMaintainerID();
  /**
   * <code>.ids.MaintainerID maintainer_i_d = 1 [json_name = "maintainerID"];</code>
   * @return The maintainerID.
   */
  com.ids.MaintainerID getMaintainerID();
  /**
   * <code>.ids.MaintainerID maintainer_i_d = 1 [json_name = "maintainerID"];</code>
   */
  com.ids.MaintainerIDOrBuilder getMaintainerIDOrBuilder();
}
