// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/orders/internal/transactions/immediate/message.v1.proto

package com.orders.transactions.immediate;

public final class MessageV1Proto {
  private MessageV1Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_orders_transactions_immediate_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_orders_transactions_immediate_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n?modules/orders/internal/transactions/i" +
      "mmediate/message.v1.proto\022\035orders.transa" +
      "ctions.immediate\032\024gogoproto/gogo.proto\032)" +
      "schema/ids/base/classificationID.v1.prot" +
      "o\032#schema/ids/base/identityID.v1.proto\032%" +
      "schema/ids/base/anyOwnableID.v1.proto\032\'s" +
      "chema/lists/base/propertyList.v1.proto\032!" +
      "schema/types/base/height.v1.proto\"\356\005\n\007Me" +
      "ssage\022\022\n\004from\030\001 \001(\tR\004from\022)\n\010from_i_d\030\002 " +
      "\001(\0132\017.ids.IdentityIDR\006fromID\022C\n\022classifi" +
      "cation_i_d\030\003 \001(\0132\025.ids.ClassificationIDR" +
      "\020classificationID\022+\n\ttaker_i_d\030\004 \001(\0132\017.i" +
      "ds.IdentityIDR\007takerID\022<\n\021maker_ownable_" +
      "i_d\030\005 \001(\0132\021.ids.AnyOwnableIDR\016makerOwnab" +
      "leID\022<\n\021taker_ownable_i_d\030\006 \001(\0132\021.ids.An" +
      "yOwnableIDR\016takerOwnableID\022,\n\nexpires_in" +
      "\030\007 \001(\0132\r.types.HeightR\texpiresIn\022.\n\023make" +
      "r_ownable_split\030\010 \001(\tR\021makerOwnableSplit" +
      "\022.\n\023taker_ownable_split\030\t \001(\tR\021takerOwna" +
      "bleSplit\022O\n\031immutable_meta_properties\030\n " +
      "\001(\0132\023.lists.PropertyListR\027immutableMetaP" +
      "roperties\022F\n\024immutable_properties\030\013 \001(\0132" +
      "\023.lists.PropertyListR\023immutablePropertie" +
      "s\022K\n\027mutable_meta_properties\030\014 \001(\0132\023.lis" +
      "ts.PropertyListR\025mutableMetaProperties\022B" +
      "\n\022mutable_properties\030\r \001(\0132\023.lists.Prope" +
      "rtyListR\021mutablePropertiesB\230\002\n!com.order" +
      "s.transactions.immediateB\016MessageV1Proto" +
      "P\001ZMgithub.com/AssetMantle/modules/modul" +
      "es/orders/internal/transactions/immediat" +
      "e\242\002\003OTI\252\002\035Orders.Transactions.Immediate\312" +
      "\002\035Orders\\Transactions\\Immediate\342\002)Orders" +
      "\\Transactions\\Immediate\\GPBMetadata\352\002\037Or" +
      "ders::Transactions::Immediateb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.gogoproto.GogoProto.getDescriptor(),
          com.ids.ClassificationIDV1Proto.getDescriptor(),
          com.ids.IdentityIDV1Proto.getDescriptor(),
          com.ids.AnyOwnableIDV1Proto.getDescriptor(),
          com.lists.PropertyListV1Proto.getDescriptor(),
          com.types.HeightV1Proto.getDescriptor(),
        });
    internal_static_orders_transactions_immediate_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_orders_transactions_immediate_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_orders_transactions_immediate_Message_descriptor,
        new java.lang.String[] { "From", "FromID", "ClassificationID", "TakerID", "MakerOwnableID", "TakerOwnableID", "ExpiresIn", "MakerOwnableSplit", "TakerOwnableSplit", "ImmutableMetaProperties", "ImmutableProperties", "MutableMetaProperties", "MutableProperties", });
    com.gogoproto.GogoProto.getDescriptor();
    com.ids.ClassificationIDV1Proto.getDescriptor();
    com.ids.IdentityIDV1Proto.getDescriptor();
    com.ids.AnyOwnableIDV1Proto.getDescriptor();
    com.lists.PropertyListV1Proto.getDescriptor();
    com.types.HeightV1Proto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
