name: Mantleplace - CI

on:
  push:
    branches:
      - main*
      - master*
    tags:
      - "**/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1
        with: { install: true }

      - name: Test Dist
        if: ${{ github.ref_type != 'tag' || github.ref != 'refs/heads/main*' || github.ref != 'refs/heads/master*' }}
        uses: docker/build-push-action@v2
        with:
          target: build
          push: false
          tags: assetmantle/mantleplace:dist-test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - id: meta
        uses: docker/metadata-action@v3
        if: ${{ github.ref_type == 'tag' }}
        with:
          images: |
            assetmantle/mantleplace
          tags: |
            type=raw,value=latest-{{sha}}-{{date 'X'}}
            type=raw,value=latest

      - id: meta-branch
        uses: docker/metadata-action@v3
        if: ${{ github.ref_type == 'branch' }}
        with:
          images: |
            assetmantle/mantleplace
          tags: |
            type=raw,value=edge-{{sha}}-{{date 'X'}}
            type=raw,value=edge

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - uses: docker/build-push-action@v2
        if: ${{ github.ref_type == 'branch' }}
        with:
          push: true
          tags: ${{ steps.meta-branch.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
