name: Mantleplace - CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup docker builder
        uses: docker/setup-buildx-action@v1
        with: { install: true }

      - name: Test sbt dist
        uses: docker/build-push-action@v2
        if: ${{ !(github.ref_type == 'tag' || (github.ref_type == 'branch' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'))) }}
        with:
          target: build
          push: false
          cache-from: type=gha

      - name: Test sbt dist (cached)
        uses: docker/build-push-action@v2
        if: ${{ github.ref_type == 'tag' || (github.ref_type == 'branch' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')) }}
        with:
          target: build
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Prepare production release tags
        id: meta
        uses: docker/metadata-action@v3
        if: ${{ github.ref_type == 'tag' }}
        with:
          images: |
            assetmantle/mantleplace
          tags: |
            type=raw,value=latest-{{sha}}-{{date 'X'}}
            type=raw,value=latest

      - name: Prepare staging release ragas
        id: meta-branch
        uses: docker/metadata-action@v3
        if: ${{ github.ref_type == 'branch' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') }}
        with:
          images: |
            assetmantle/mantleplace
          tags: |
            type=raw,value=edge-{{sha}}-{{date 'X'}}
            type=raw,value=edge

      - name: Login to docker registry
        uses: docker/login-action@v1
        if: ${{ github.ref_type == 'tag' || (github.ref_type == 'branch' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')) }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build production container image
        uses: docker/build-push-action@v2
        if: ${{ github.ref_type == 'tag' }}
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build staging container image
        uses: docker/build-push-action@v2
        if: ${{ github.ref_type == 'branch' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') }}
        with:
          push: true
          tags: ${{ steps.meta-branch.outputs.tags }}
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run container vulnerability scanner
        if: ${{ github.ref_type == 'tag' }}
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'assetmantle/mantleplace:latest'
          format: 'table'
          exit-code: '0'
          vuln-type: 'os,library'

      - name: Run container vulnerability scanner
        if: ${{ github.ref_type == 'branch' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') }}
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'assetmantle/mantleplace:edge'
          format: 'table'
          exit-code: '0'
          vuln-type: 'os,library'
