
name: Mantleplace - Test

on:
  push:
    branches:
      - develop*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with: { install: true }
      - name: Test Dist
        uses: docker/build-push-action@v2
        with:
          target: build
          push: false
          tags: assetmantle/mantleplace:dist-test
          cache-from: type=gha
          cache-to: type=gha,mode=max
