// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/splits/internal/transactions/send/response.v1.proto

package com.splits.transactions.send;

public final class ResponseV1Proto {
  private ResponseV1Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_splits_transactions_send_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_splits_transactions_send_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n;modules/splits/internal/transactions/s" +
      "end/response.v1.proto\022\030splits.transactio" +
      "ns.send\"\n\n\010ResponseB\373\001\n\034com.splits.trans" +
      "actions.sendB\017ResponseV1ProtoP\001ZHgithub." +
      "com/AssetMantle/modules/modules/splits/i" +
      "nternal/transactions/send\242\002\003STS\252\002\030Splits" +
      ".Transactions.Send\312\002\030Splits\\Transactions" +
      "\\Send\342\002$Splits\\Transactions\\Send\\GPBMeta" +
      "data\352\002\032Splits::Transactions::Sendb\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_splits_transactions_send_Response_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_splits_transactions_send_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_splits_transactions_send_Response_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
