// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/splits/internal/transactions/send/transactionService.v1.proto

package com.splits.transactions.send;

public final class TransactionServiceV1Proto {
  private TransactionServiceV1Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nEmodules/splits/internal/transactions/s" +
      "end/transactionService.v1.proto\022\030splits." +
      "transactions.send\032\034google/api/annotation" +
      "s.proto\032:modules/splits/internal/transac" +
      "tions/send/message.v1.proto\032Fmodules/spl" +
      "its/internal/transactions/send/transacti" +
      "onResponse.v1.proto2\204\001\n\013Transaction\022u\n\004S" +
      "end\022!.splits.transactions.send.Message\032-" +
      ".splits.transactions.send.TransactionRes" +
      "ponse\"\033\202\323\344\223\002\025\"\023/mantle/splits/sendB\205\002\n\034c" +
      "om.splits.transactions.sendB\031Transaction" +
      "ServiceV1ProtoP\001ZHgithub.com/AssetMantle" +
      "/modules/modules/splits/internal/transac" +
      "tions/send\242\002\003STS\252\002\030Splits.Transactions.S" +
      "end\312\002\030Splits\\Transactions\\Send\342\002$Splits\\" +
      "Transactions\\Send\\GPBMetadata\352\002\032Splits::" +
      "Transactions::Sendb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.splits.transactions.send.MessageV1Proto.getDescriptor(),
          com.splits.transactions.send.TransactionResponseV1Proto.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.splits.transactions.send.MessageV1Proto.getDescriptor();
    com.splits.transactions.send.TransactionResponseV1Proto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
